# Generated by Django 2.2.6 on 2021-03-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210321_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': ('Сообщество',), 'verbose_name_plural': ('Сообщества',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': ('Запись',), 'verbose_name_plural': ('Записи',)},
        ),
    ]
