# Generated by Django 2.2.6 on 2021-04-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20210412_0920'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_object',
        ),
    ]
